"""empty message

Revision ID: 5c4030228247
Revises: 89c06b82a23d
Create Date: 2023-04-06 16:44:06.006425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4030228247'
down_revision = '89c06b82a23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'created_at')
    # ### end Alembic commands ###
