"""empty message

Revision ID: 80fb4b2984b5
Revises: a335840f42a7
Create Date: 2023-04-09 02:40:01.141952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80fb4b2984b5'
down_revision = 'a335840f42a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='followers_follower_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='followers_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'follower_id', name='followers_pkey')
    )
    # ### end Alembic commands ###
