"""empty message

Revision ID: 00b560b5031d
Revises: 5c4030228247
Create Date: 2023-04-06 19:02:20.374496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b560b5031d'
down_revision = '5c4030228247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('followers_followed_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['user_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_followed_id_fkey', 'followers', 'users', ['followed_id'], ['id'])
    op.drop_column('followers', 'user_id')
    # ### end Alembic commands ###
